BEGIN
        DENOTED TITLE;
        TITLE := "ENTER A TEXT WITHOUT QUOTES, CTRL-D to finish FOR  DENOTED VARIABLE TEST 3\n";
 
        OUTPUT TITLE;      
	
	DENOTED A;
	INPUT A;
       
        OUTPUT A
END